USE display_manufacturing;

CREATE TABLE IF NOT EXISTS prod_line_station (
  station_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  station_code VARCHAR(32) NOT NULL,
  station_name VARCHAR(64) NOT NULL,
  line_code VARCHAR(16) NOT NULL DEFAULT 'LINE-A',
  sort_no INT NOT NULL DEFAULT 0,
  station_status VARCHAR(20) NOT NULL DEFAULT 'IDLE',
  current_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  throughput_per_hour DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  equipment_id BIGINT UNSIGNED NULL,
  work_order_id BIGINT UNSIGNED NULL,
  work_order_no VARCHAR(50) NULL,
  alarm_flag TINYINT NOT NULL DEFAULT 0,
  remark VARCHAR(200) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_station_code (station_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prod_hourly_metric (
  metric_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stat_date DATE NOT NULL,
  stat_hour TINYINT NOT NULL,
  planned_output DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  actual_output DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  qualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  unqualified_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  alarm_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_date_hour (stat_date, stat_hour)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prod_shift_capacity (
  capacity_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stat_date DATE NOT NULL,
  team_code VARCHAR(32) NOT NULL,
  team_name VARCHAR(64) NOT NULL,
  leader_name VARCHAR(32) NULL,
  planned_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  actual_qty DECIMAL(18,4) NOT NULL DEFAULT 0.0000,
  yield_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  rank_no INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_date_team (stat_date, team_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prod_downtime_reason (
  reason_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  stat_date DATE NOT NULL,
  reason_code VARCHAR(32) NOT NULL,
  reason_name VARCHAR(100) NOT NULL,
  downtime_minutes INT NOT NULL DEFAULT 0,
  occurrence_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_date_reason (stat_date, reason_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
